import { Button } from './components/ui';

export const App = () => (
  <>
    <Button
      color="primary"
      variant="contained"
    >
      Button
    </Button>
    <Button
      color="primary"
      variant="contained"
      disabled
    >
      Button
    </Button>
    <Button
      color="primary"
      variant="text"
    >
      Button
    </Button>
    <Button
      color="primary"
      variant="text"
      disabled
    >
      Button
    </Button>
    <Button
      color="secondary"
      variant="contained"
    >
      Button
    </Button>
    <Button
      color="secondary"
      variant="contained"
      disabled
    >
      Button
    </Button>
    <Button
      color="secondary"
      variant="text"
    >
      Button
    </Button>
    <Button
      color="secondary"
      variant="text"
      disabled
    >
      Button
    </Button>
  </>
);
